# Generated by Django 5.2.12 on 2026-03-14 01:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('receptionist_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف موظف الاستقبال')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='الراتب الشهري (اختياري)', max_digits=10, null=True, verbose_name='الراتب')),
                ('work_type', models.CharField(blank=True, help_text='مثال: دوام كامل، دوام جزئي، نوبات (اختياري)', max_length=100, null=True, verbose_name='نوع العمل')),
                ('working_hours', models.PositiveIntegerField(blank=True, help_text='عدد الساعات الأسبوعية أو اليومية (اختياري)', null=True, verbose_name='عدد ساعات العمل')),
                ('shift_start_time', models.TimeField(blank=True, help_text='وقت بداية الدوام اليومي (اختياري)', null=True, verbose_name='بداية الدوام')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'receptionist'}, on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'موظف استقبال',
                'verbose_name_plural': 'موظفي الاستقبال',
                'ordering': ['-created_at'],
            },
        ),
    ]
