# Generated by Django 6.0.3 on 2026-04-06 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("lab_reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportSharing",
            fields=[
                (
                    "share_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="معرف المشاركة",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "عرض فقط"),
                            ("view_download", "عرض + تحميل"),
                            ("edit", "تعديل (نادر)"),
                            ("full_access", "وصول كامل (نادر جدًا)"),
                        ],
                        default="view",
                        max_length=20,
                        verbose_name="مستوى الصلاحية",
                    ),
                ),
                (
                    "shared_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ المشاركة"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="اختياري: متى تنتهي صلاحية المشاركة",
                        null=True,
                        verbose_name="تاريخ انتهاء الصلاحية",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sharings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="من قام بالمشاركة",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_reports",
                        to="lab_reports.labreport",
                        verbose_name="التقرير المشترك",
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_reports",
                        to="doctors.doctor",
                        verbose_name="الطبيب المشترك معه",
                    ),
                ),
            ],
            options={
                "verbose_name": "مشاركة تقرير",
                "verbose_name_plural": "مشاركات التقارير",
                "ordering": ["-shared_at"],
                "indexes": [
                    models.Index(
                        fields=["report", "shared_with"],
                        name="report_shar_report__8fa898_idx",
                    )
                ],
                "unique_together": {("report", "shared_with")},
            },
        ),
    ]
