# Generated by Django 5.2.12 on 2026-03-10 23:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('report_sharing', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsharing',
            options={'ordering': ['-shared_at']},
        ),
        migrations.RemoveIndex(
            model_name='reportsharing',
            name='report_shar_report__8fa898_idx',
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sharings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='permission',
            field=models.CharField(choices=[('view', 'عرض فقط'), ('view_download', 'عرض + تحميل'), ('edit', 'تعديل (نادر)'), ('full_access', 'وصول كامل (نادر جدًا)')], default='view', max_length=20),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='reports.labreports'),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='shared_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to='doctors.doctor'),
        ),
    ]
