# Generated by Django 5.2.12 on 2026-03-11 00:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('report_sharing', '0002_alter_reportsharing_options_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportsharing',
            options={'ordering': ['-shared_at'], 'verbose_name': 'مشاركة تقرير', 'verbose_name_plural': 'مشاركات التقارير'},
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sharings', to=settings.AUTH_USER_MODEL, verbose_name='من قام بالمشاركة'),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='اختياري: متى تنتهي صلاحية المشاركة', null=True, verbose_name='تاريخ انتهاء الصلاحية'),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='permission',
            field=models.CharField(choices=[('view', 'عرض فقط'), ('view_download', 'عرض + تحميل'), ('edit', 'تعديل (نادر)'), ('full_access', 'وصول كامل (نادر جدًا)')], default='view', max_length=20, verbose_name='مستوى الصلاحية'),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharings', to='reports.labreports', verbose_name='التقرير المشترك'),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='share_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف المشاركة'),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='shared_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ المشاركة'),
        ),
        migrations.AlterField(
            model_name='reportsharing',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_reports', to='doctors.doctor', verbose_name='الطبيب المشترك معه'),
        ),
        migrations.AddIndex(
            model_name='reportsharing',
            index=models.Index(fields=['report', 'shared_with'], name='report_shar_report__8fa898_idx'),
        ),
    ]
