# Generated by Django 5.2.12 on 2026-03-10 15:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('note_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف الملاحظة')),
                ('note_text', models.TextField(help_text='اكتب الملاحظات الطبية، التشخيص، التوصيات، المتابعة...', verbose_name='نص الملاحظة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='doctors.doctor', verbose_name='الطبيب')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_notes', to='patients.patient', verbose_name='المريض')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_notes', to='reports.labreports', verbose_name='التقرير المرتبط (اختياري)')),
            ],
            options={
                'verbose_name': 'ملاحظة طبيب',
                'verbose_name_plural': 'ملاحظات الأطباء',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'patient'], name='doctor_note_doctor__a98156_idx')],
            },
        ),
    ]
