# Generated by Django 6.0.3 on 2026-04-06 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_analysis", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthAlert",
            fields=[
                (
                    "alert_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="معرف التنبيه",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("critical", "حرج / طارئ"),
                            ("warning", "تحذير"),
                            ("info", "معلوماتي / تذكير"),
                            ("follow_up", "متابعة موعد"),
                            ("abnormal_result", "نتيجة غير طبيعية"),
                        ],
                        default="info",
                        max_length=50,
                        verbose_name="نوع التنبيه",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="نص التنبيه اللي رح يشوفه المريض (مثال: 'نتيجة التحليل تشير إلى ارتفاع في السكر، يرجى زيارة الطبيب')",
                        verbose_name="رسالة التنبيه",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء؟")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_alerts",
                        to="patients.patient",
                        verbose_name="المريض",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_alerts",
                        to="ai_analysis.aianalysis",
                        verbose_name="نتيجة التحليل المرتبطة (اختياري)",
                    ),
                ),
            ],
            options={
                "verbose_name": "تنبيه صحي",
                "verbose_name_plural": "تنبيهات صحية",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "created_at"],
                        name="health_aler_patient_767811_idx",
                    ),
                    models.Index(
                        fields=["is_read"], name="health_aler_is_read_4611dd_idx"
                    ),
                ],
            },
        ),
    ]
