# Generated by Django 6.0.3 on 2026-04-06 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab_reports", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "analysis_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="معرف التحليل",
                    ),
                ),
                (
                    "prediction",
                    models.CharField(
                        help_text="مثال: 'التهاب رئوي'، 'طبيعي'، 'خطر متوسط'...",
                        max_length=255,
                        verbose_name="التنبؤ / النتيجة",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        blank=True,
                        help_text="قيمة بين 0.0 و 1.0 (مثال: 0.92 = 92% ثقة)",
                        null=True,
                        verbose_name="درجة الثقة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التحليل"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True,
                        help_text="مثال: v1.2.3 أو 'resnet50'",
                        max_length=50,
                        verbose_name="إصدار النموذج",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="patients.patient",
                        verbose_name="المريض",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_analyses",
                        to="lab_reports.labreport",
                        verbose_name="التقرير المرتبط (اختياري)",
                    ),
                ),
            ],
            options={
                "verbose_name": "تحليل ذكاء اصطناعي",
                "verbose_name_plural": "تحاليل الذكاء الاصطناعي",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "created_at"],
                        name="ai_analysis_patient_08bfee_idx",
                    )
                ],
            },
        ),
    ]
