# Generated by Django 6.0.3 on 2026-04-06 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lab_tests", "0001_initial"),
        ("patients", "0001_initial"),
        ("test_results", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientTestHistory",
            fields=[
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="معرف السجل التاريخي",
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        help_text="القيمة الفعلية في هذا التاريخ",
                        verbose_name="القيمة المسجلة",
                    ),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="الوحدة"),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ التسجيل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "طبيعي"),
                            ("low", "منخفض"),
                            ("high", "مرتفع"),
                            ("abnormal", "غير طبيعي"),
                            ("critical", "حرج"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="حالة النتيجة",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات إضافية")),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_history",
                        to="patients.patient",
                        verbose_name="المريض",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_entries",
                        to="test_results.testresult",
                        verbose_name="النتيجة المرتبطة (اختياري)",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_history",
                        to="lab_tests.labtest",
                        verbose_name="نوع التحليل",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل تاريخي لتحليل",
                "verbose_name_plural": "سجلات تاريخ التحاليل",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "test", "recorded_at"],
                        name="patient_tes_patient_d4ce78_idx",
                    )
                ],
            },
        ),
    ]
