# Generated by Django 6.0.3 on 2026-04-06 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="معرف المستخدم",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="البريد الإلكتروني",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="الاسم الكامل")),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        help_text="رقم وطني مكون من 11 إلى 15 رقم",
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="الرقم الوطني",
                    ),
                ),
                (
                    "random_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Example: PAT-2026-7891234 — Automatically generated",
                        max_length=24,
                        verbose_name="كود عشوائي",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("patient", "مريض"),
                            ("doctor", "طبيب"),
                            ("admin", "إداري"),
                            ("receptionist", "استقبال"),
                            ("lab_technician", "مخبري"),
                        ],
                        default="patient",
                        max_length=20,
                        verbose_name="الدور",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "ذكر"), ("female", "أنثى"), ("other", "آخر")],
                        max_length=10,
                        verbose_name="الجنس",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="رقم الهاتف")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر تسجيل دخول"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="عضو في الإدارة"),
                ),
                (
                    "password_reset_code",
                    models.CharField(blank=True, max_length=6, null=True),
                ),
                (
                    "password_reset_code_expiry",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمين",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.TextField(verbose_name="الإجراء / الوصف")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإجراء"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "سجل نشاط",
                "verbose_name_plural": "سجلات النشاط",
                "ordering": ["-created_at"],
            },
        ),
    ]
