# Generated by Django 5.2.12 on 2026-03-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, help_text='رقم وطني مكون من 11 إلى 15 رقم', max_length=15, null=True, unique=True, verbose_name='الرقم الوطني'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='random_code',
            field=models.CharField(blank=True, editable=False, help_text='كود 10 أرقام يُولد تلقائيًا', max_length=10, verbose_name='كود عشوائي'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('patient', 'مريض'), ('doctor', 'طبيب'), ('admin', 'إداري'), ('receptionist', 'استقبال'), ('lab_technician', 'مخبري')], default='patient', max_length=20, verbose_name='الدور'),
        ),
    ]
