# Generated by Django 6.0.3 on 2026-04-06 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("lab_reports", "0001_initial"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="report_review",
            fields=[
                (
                    "review_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="معرف المراجعة",
                    ),
                ),
                (
                    "clinical_finding",
                    models.TextField(
                        help_text="What did the doctor see in the lab results or imaging? Describe any abnormalities, patterns, or significant findings.",
                        verbose_name="النتائج السريرية",
                    ),
                ),
                (
                    "diagnosis",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="التشخيص المبدئي/النهائي",
                    ),
                ),
                (
                    "comparison_with_previous",
                    models.TextField(
                        blank=True,
                        help_text="Compare the current report with previous ones. Is there improvement, deterioration, or stability? This helps in understanding the progression of the patient's condition.",
                        verbose_name="مقارنة مع تقارير سابقة",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(
                        help_text="Based on the findings, what are your recommendations for the next steps? This could include further tests, referrals to specialists, or specific treatments.",
                        verbose_name="التوصيات الطبية",
                    ),
                ),
                (
                    "prescribed_medication",
                    models.TextField(
                        blank=True, verbose_name="الأدوية الموصوفة بناءً على التقرير"
                    ),
                ),
                (
                    "require_urgent_action",
                    models.BooleanField(
                        default=False, verbose_name="يتطلب إجراء عاجل؟"
                    ),
                ),
                (
                    "result_interpretation",
                    models.CharField(
                        choices=[
                            ("normal", "نتائج طبيعية"),
                            ("abnormal", "نتائج غير طبيعية - مستقرة"),
                            ("critical", "حالة حرجة"),
                            ("inconclusive", "غير حاسم - يتطلب فحوصات إضافية"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="تفسير الحالة",
                    ),
                ),
                (
                    "doctor_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الطبيب الخاصة"),
                ),
                (
                    "review_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ المراجعة"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doctor_reviews",
                        to="doctors.doctor",
                        verbose_name="الطبيب المراجع",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_reviews",
                        to="patients.patient",
                        verbose_name="المريض",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="lab_reports.labreport",
                        verbose_name="التقرير الأصلي",
                    ),
                ),
            ],
            options={
                "verbose_name": "مراجعة طبية",
                "verbose_name_plural": "مراجعات طبية",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "patient"],
                        name="report_revi_doctor__bda0d3_idx",
                    )
                ],
            },
        ),
    ]
