# Generated by Django 5.2.12 on 2026-03-10 23:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف الصورة')),
                ('image_path', models.ImageField(help_text='صورة التقرير، التحليل، الأشعة أو الوثيقة', upload_to='report_images/%Y/%m/%d/', verbose_name='مسار الصورة')),
                ('ocr_confidence', models.FloatField(blank=True, help_text='من 0.0 إلى 1.0 إذا تم استخراج نص تلقائيًا', null=True, verbose_name='درجة ثقة الـ OCR')),
                ('ocr_text', models.TextField(blank=True, help_text='النص اللي تم استخراجه من الصورة (إذا نجح OCR)', null=True, verbose_name='النص المستخرج بالـ OCR')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الرفع')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lab_reports.labreport', verbose_name='التقرير المرتبط')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_report_images', to=settings.AUTH_USER_MODEL, verbose_name='من رفع الصورة')),
            ],
            options={
                'verbose_name': 'صورة تقرير',
                'verbose_name_plural': 'صور التقارير',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['report', 'uploaded_at'], name='report_imag_report__991dc4_idx')],
            },
        ),
    ]
