# Generated by Django 5.2.12 on 2026-03-10 14:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReports',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف التقرير')),
                ('lab_name', models.CharField(max_length=255, verbose_name='اسم المختبر')),
                ('report_date', models.DateField(verbose_name='تاريخ التقرير')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الرفع')),
                ('file_path', models.FileField(blank=True, null=True, upload_to='lab_reports/%Y/%m/%d/', verbose_name='مسار الملف')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('processing', 'جاري المعالجة')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL, verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'تقرير مختبر',
                'verbose_name_plural': 'تقارير المختبر',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportImages',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف الصورة')),
                ('image_path', models.ImageField(upload_to='report_images/%Y/%m/%d/', verbose_name='مسار الصورة')),
                ('ocr_confidence', models.FloatField(blank=True, help_text='من 0.0 إلى 1.0', null=True, verbose_name='درجة ثقة الـ OCR')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.labreports', verbose_name='التقرير المرتبط')),
            ],
            options={
                'verbose_name': 'صورة تقرير',
                'verbose_name_plural': 'صور التقارير',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
