# Generated by Django 5.2.12 on 2026-03-14 01:41

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTechnician',
            fields=[
                ('technician_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف المخبري')),
                ('lab_specialty', models.CharField(blank=True, help_text='مثال: تحاليل دم، أشعة، باثولوجي...', max_length=255, verbose_name='تخصص المختبر')),
                ('license_number', models.CharField(blank=True, help_text='رقم الترخيص المهني للمخبري (اختياري)', max_length=100, unique=True, verbose_name='رقم ترخيص المختبر')),
                ('lab_location', models.CharField(blank=True, help_text='اسم المختبر أو العنوان (مثال: مختبر الشام - دمشق، حي المزة)', max_length=255, null=True, verbose_name='موقع المختبر')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنوات الخبرة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'lab_technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_technician_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'مخبري',
                'verbose_name_plural': 'المخبريين',
                'ordering': ['-created_at'],
            },
        ),
    ]
