# Generated by Django 5.2.12 on 2026-03-10 23:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lab_tests', '0001_initial'),
        ('patients', '0001_initial'),
        ('test_results', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestComparison',
            fields=[
                ('comparison_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف المقارنة')),
                ('trend', models.CharField(choices=[('improved', 'تحسن'), ('worsened', 'تدهور'), ('stable', 'مستقر'), ('significant_change', 'تغيير كبير'), ('new_baseline', 'قاعدة جديدة')], default='stable', max_length=30, verbose_name='الاتجاه / النتيجة')),
                ('change_percentage', models.FloatField(blank=True, help_text='نسبة التغيير بين القديم والجديد (موجب أو سالب)', null=True, verbose_name='نسبة التغيير (%)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ المقارنة')),
                ('new_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_comparisons', to='test_results.testresult', verbose_name='النتيجة الجديدة')),
                ('old_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_comparisons', to='test_results.testresult', verbose_name='النتيجة القديمة')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_comparisons', to='patients.patient', verbose_name='المريض')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons', to='lab_tests.labtest', verbose_name='نوع التحليل')),
            ],
            options={
                'verbose_name': 'مقارنة تحليل',
                'verbose_name_plural': 'مقارنات التحاليل',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'test', 'created_at'], name='test_compar_patient_0d323c_idx')],
                'unique_together': {('patient', 'test', 'new_result')},
            },
        ),
    ]
