# Generated by Django 5.2.12 on 2026-03-10 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('test_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف التحليل')),
                ('test_name', models.CharField(help_text='مثال: Glucose, Hemoglobin, TSH...', max_length=255, verbose_name='اسم التحليل')),
                ('loinc_code', models.CharField(blank=True, help_text='الكود الدولي من Logical Observation Identifiers Names and Codes', max_length=50, verbose_name='كود LOINC')),
                ('category', models.CharField(blank=True, help_text='مثال: Hematology, Biochemistry, Endocrinology, Microbiology...', max_length=100, verbose_name='الفئة')),
                ('normal_range_min', models.FloatField(blank=True, null=True, verbose_name='الحد الأدنى الطبيعي')),
                ('normal_range_max', models.FloatField(blank=True, null=True, verbose_name='الحد الأعلى الطبيعي')),
                ('unit', models.CharField(blank=True, help_text='مثال: mg/dL, g/L, IU/mL, %...', max_length=50, verbose_name='الوحدة')),
                ('description', models.TextField(blank=True, help_text='معلومات إضافية عن التحليل أو الطريقة', verbose_name='الوصف / الملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'تحليل مخبري',
                'verbose_name_plural': 'التحاليل المخبرية',
                'ordering': ['test_name'],
                'indexes': [models.Index(fields=['test_name'], name='lab_tests_l_test_na_1f37b8_idx'), models.Index(fields=['loinc_code'], name='lab_tests_l_loinc_c_7bae1f_idx')],
                'unique_together': {('test_name', 'loinc_code')},
            },
        ),
    ]
