# Generated by Django 6.0.3 on 2026-04-06 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_analysis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interpretation",
            fields=[
                (
                    "interpretation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="معرف التفسير",
                    ),
                ),
                (
                    "interpretation_text",
                    models.TextField(
                        help_text="التفسير الطبي أو التحليلي للنتيجة (مثال: 'ارتفاع في السكر يشير إلى احتمال سكري نوع 2')",
                        verbose_name="نص التفسير",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("normal", "طبيعي"),
                            ("mild", "خفيف"),
                            ("moderate", "متوسط"),
                            ("severe", "شديد"),
                            ("critical", "حرج / طارئ"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="درجة الخطورة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_interpretations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="من أنشأ التفسير (AI أو طبيب)",
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretations",
                        to="ai_analysis.aianalysis",
                        verbose_name="النتيجة / التحليل المرتبط",
                    ),
                ),
            ],
            options={
                "verbose_name": "تفسير نتيجة",
                "verbose_name_plural": "تفسيرات النتائج",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["result", "created_at"],
                        name="interpretat_result__b2e719_idx",
                    )
                ],
            },
        ),
    ]
