# Generated by Django 5.2.12 on 2026-03-10 15:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف المريض')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'غير معروف')], default='unknown', max_length=7, verbose_name='فصيلة الدم')),
                ('chronic_diseases', models.TextField(blank=True, help_text='اكتب الأمراض المزمنة مفصولة بفواصل أو سطور جديدة', verbose_name='الأمراض المزمنة')),
                ('allergies', models.TextField(blank=True, help_text='اكتب أنواع الحساسية (أدوية، طعام، مواد...) مفصولة بفواصل', verbose_name='الحساسية')),
                ('height', models.FloatField(blank=True, help_text='بالسنتيمتر (مثال: 175.5)', null=True, verbose_name='الطول')),
                ('weight', models.FloatField(blank=True, help_text='بالكيلوغرام (مثال: 75.0)', null=True, verbose_name='الوزن')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['-created_at'],
            },
        ),
    ]
