# Generated by Django 5.2.12 on 2026-03-10 15:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف الطبيب')),
                ('specialization', models.CharField(help_text='مثال: جراحة عامة، طب أسنان، أمراض قلب...', max_length=255, verbose_name='التخصص')),
                ('hospital', models.CharField(blank=True, help_text='اسم المستشفى أو العيادة الرئيسية', max_length=255, verbose_name='المستشفى / العيادة')),
                ('license_number', models.CharField(help_text='رقم ترخيص مزاولة المهنة من النقابة أو الجهة الرسمية', max_length=100, unique=True, verbose_name='رقم الترخيص المهني')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'طبيب',
                'verbose_name_plural': 'الأطباء',
                'ordering': ['-created_at'],
            },
        ),
    ]
