# Generated by Django 6.0.3 on 2026-04-06 08:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabReport",
            fields=[
                (
                    "report_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="معرف التقرير",
                    ),
                ),
                (
                    "body_part",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("head", "الرأس / الدماغ"),
                            ("neck", "الرقبة"),
                            ("chest", "الصدر"),
                            ("heart", "القلب"),
                            ("abdomen", "البطن"),
                            ("pelvis", "الحوض"),
                            ("spine", "العمود الفقري / الظهر"),
                            ("upper_limbs", "الأطراف العلوية (يد/كتف)"),
                            ("lower_limbs", "الأطراف السفلية (رجل/ركبة)"),
                            ("teeth", "الأسنان"),
                            ("eyes", "العيون"),
                            ("full_body", "كامل الجسم"),
                            ("other", "غير ذلك / غير محدد"),
                        ],
                        help_text="The Part of the body that was examined (leave blank for laboratory tests)",
                        max_length=20,
                        null=True,
                        verbose_name="الجزء المستهدف من الجسم",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("laboratory", "تحاليل مخبرية"),
                            ("radiology", "تحاليل شعاعية / تصوير طبي"),
                            ("pathology", "تحاليل نسجية (خزعات)"),
                            ("functional", "تحاليل وظيفية (تخطيط)"),
                            ("genetic", "تحاليل جينية"),
                            ("nuclear", "تحاليل نووية"),
                            ("endoscopy", "تنظير"),
                            ("other", "أخرى"),
                        ],
                        default="laboratory",
                        max_length=50,
                        verbose_name="نوع التحليل",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("blood", "تحليل دم"),
                            ("urine", "تحليل بول"),
                            ("hormones", "تحليل هرمونات"),
                            ("biochemistry", "كيمياء حيوية"),
                            ("microbiology", "أحياء دقيقة / زراعة"),
                            ("xray", "أشعة سينية (X-Ray)"),
                            ("ct", "تصوير طبقي محوري (CT)"),
                            ("mri", "رنين مغناطيسي (MRI)"),
                            ("ultrasound", "سونار / موجات فوق صوتية"),
                            ("ecg", "تخطيط قلب"),
                            ("eeg", "تخطيط دماغ"),
                            ("biopsy", "خزعة نسيجية"),
                            ("dna", "فحص حمض نووي"),
                            ("other", "أخرى"),
                        ],
                        default="blood",
                        max_length=50,
                        verbose_name="نوع التقرير",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="عنوان التقرير"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف التقرير"),
                ),
                (
                    "lab_name",
                    models.CharField(
                        help_text="اسم المختبر اللي عمل التحليل",
                        max_length=255,
                        verbose_name="اسم المختبر / المركز",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("normal", "عادي"),
                            ("urgent", "مستعجل"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(
                        help_text="تاريخ إصدار التقرير الرسمي",
                        verbose_name="تاريخ التقرير",
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاريخ الرفع"
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="lab_reports/%Y/%m/%d/",
                        verbose_name="ملف التقرير",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("processing", "جاري المعالجة"),
                            ("completed", "مكتمل"),
                            ("reviewed", "تمت المراجعة"),
                            ("rejected", "مرفوض"),
                            ("archived", "مؤرشف"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="حالة التقرير",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="تكلفة التحليل",
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء في النظام"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_lab_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="من رفع التقرير",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_reports",
                        to="patients.patient",
                        verbose_name="المريض",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقرير مختبر",
                "verbose_name_plural": "تقارير المختبر",
                "ordering": ["-upload_date"],
                "indexes": [
                    models.Index(
                        fields=["patient", "report_date"],
                        name="lab_reports_patient_dd1c40_idx",
                    ),
                    models.Index(
                        fields=["status"], name="lab_reports_status_de9b3b_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="lab_reports_priorit_fb0d88_idx"
                    ),
                ],
            },
        ),
    ]
