# Generated by Django 5.2.12 on 2026-03-10 23:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='معرف التقرير')),
                ('lab_name', models.CharField(help_text='اسم المختبر اللي عمل التحليل', max_length=255, verbose_name='اسم المختبر / المركز')),
                ('report_date', models.DateField(help_text='تاريخ إصدار التقرير الرسمي', verbose_name='تاريخ التقرير')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الرفع إلى النظام')),
                ('file_path', models.FileField(blank=True, help_text='الملف PDF أو الصورة الأصلية للتقرير', null=True, upload_to='lab_reports/%Y/%m/%d/', verbose_name='مسار الملف / التقرير')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'جاري المعالجة'), ('completed', 'مكتمل'), ('reviewed', 'تمت المراجعة'), ('rejected', 'مرفوض'), ('archived', 'مؤرشف')], default='pending', max_length=20, verbose_name='حالة التقرير')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء في النظام')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lab_reports', to=settings.AUTH_USER_MODEL, verbose_name='من رفع التقرير')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patients.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'تقرير مختبر',
                'verbose_name_plural': 'تقارير المختبر',
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['patient', 'report_date'], name='lab_reports_patient_dd1c40_idx'), models.Index(fields=['status'], name='lab_reports_status_de9b3b_idx')],
            },
        ),
    ]
